version: "3.9"

services:
  movtorrentbot:
    build: .
    container_name: movtorrentbot
    volumes:
      - ./config.yml:/config.yml:ro
      - ./queue:/queue
      - /mnt/media/Movies:/downloads/movies:rw
      - /mnt/media/Shows:/downloads/series:rw
      - ./qbt-profile:/.qbt:rw
    command: ["--config", "/config.yml"]
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-Xmx512m"
    ports:
      - "8080:8080"  # qBittorrent Web UI if needed